name: CoolFly
main: CoolFly\Main
version: 1.0.0
api: [3.5.6, 3.0.0, 4.0.0]
author: benzodoespvp
description: Advanced Fly Plugin
commands:
 fly:
  description: "Enables /fly"
  permissions:
   fly.use
