name: CoolFly
main: CoolFly\Main
version: 1.0.0
api: [3.5.6]
author: benzodoespvp
description: Advanced Fly Plugin

commands:
    fly:
       description: Enable fly
       permission: fly.use
